name: flutter_passkey_kit
description: "Flutter Passkey Kit for Soroban Smart Wallets"
version: 0.0.1
repository: https://github.com/Soneso/flutter_passkey_kit

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  stellar_flutter_sdk: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
